### ISSUE TITLE
npm install remark-lint-no-trailing-slash

### ISSUE THREAD

**Issue by sobolevn** [vhf/remark-lint-no-url-trailing-slash#1]
This fails with this message:

> [16:32:32] sobolev :: MacBook-Pro-Nikita  ➜  Documents/github/awesome-cryptography ‹master*› » npm install remark-lint-no-trailing-slash                    1 ↵
> npm ERR! Darwin 15.5.0
> npm ERR! argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "install" "remark-lint-no-trailing-slash"
> npm ERR! node v5.5.0
> npm ERR! npm  v3.5.3
> npm ERR! code E404
> 
> npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/remark-lint-no-trailing-slash
> npm ERR! 404 
> npm ERR! 404  'remark-lint-no-trailing-slash' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404 
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/sobolev/Documents/github/awesome-cryptography/npm-debug.log

**Comment by vhf** [comment]
Thanks, and sorry about that. The correct npm package is this one :
https://www.npmjs.com/package/remark-lint-no-url-trailing-slash

Notice the -url-.

I'll fix the readme asap.

**Comment by sobolevn** [comment]
Thanks, that works!
