### ISSUE TITLE
The tool is failing for me.

### ISSUE THREAD

**Issue by sobolevn** [vhf/remark-lint-no-url-trailing-slash#2]
I am trying to integrate this tool with my [`awesome-cryptography` list](https://github.com/sobolevn/awesome-cryptography). But it dies with exceptions for some reason:

My setup:

```
"remarkConfig": {
    "plugins": {
      "lint": {
        "maximum-line-length": 350,
        "list-item-indent": "space",
        "no-tabs": null,
        "external": [
          "remark-lint-alphabetize-lists",
          "remark-lint-no-url-trailing-slash"
        ]
      }
    },
    ...

```

Here's the output:

> [16:47:41] sobolev :: MacBook-Pro-Nikita  ➜  Documents/github/awesome-cryptography ‹master*› » npm test                                                     1 ↵
> 
> > awesome-cryptography@1.0.0 test /Users/sobolev/Documents/github/awesome-cryptography
> > ./node_modules/remark/bin/remark README.md CONTRIBUTING.md -f
> 
> README.md
>         1:1  error    TypeError: Parameter 'url' must be a string, not undefined
>     at Url.parse (url.js:90:11)
>     at Object.urlParse [as parse](url.js:84:5)
>     at /Users/sobolev/Documents/github/awesome-cryptography/node_modules/remark-lint-no-url-trailing-slash/dist/resource-url.js:9:22
>     at one (/Users/sobolev/Documents/github/awesome-cryptography/node_modules/unist-util-visit/index.js:72:22)
>     at all (/Users/sobolev/Documents/github/awesome-cryptography/node_modules/unist-util-visit/index.js:48:26)
>     at one (/Users/sobolev/Documents/github/awesome-cryptography/node_modules/unist-util-visit/index.js:76:20)
>     at all (/Users/sobolev/Documents/github/awesome-cryptography/node_modules/unist-util-visit/index.js:48:26)
>     at one (/Users/sobolev/Documents/github/awesome-cryptography/node_modules/unist-util-visit/index.js:76:20)
>     at visit (/Users/sobolev/Documents/github/awesome-cryptography/node_modules/unist-util-visit/index.js:82:5)
>     at checkURL (/Users/sobolev/Documents/github/awesome-cryptography/node_modules/remark-lint-no-url-trailing-slash/dist/resource-url.js:7:3)
> 
> CONTRIBUTING.md
>         1:1  error    TypeError: Parameter 'url' must be a string, not undefined
>     at Url.parse (url.js:90:11)
>     at Object.urlParse [as parse](url.js:84:5)
>     at /Users/sobolev/Documents/github/awesome-cryptography/node_modules/remark-lint-no-url-trailing-slash/dist/resource-url.js:9:22
>     at one (/Users/sobolev/Documents/github/awesome-cryptography/node_modules/unist-util-visit/index.js:72:22)
>     at all (/Users/sobolev/Documents/github/awesome-cryptography/node_modules/unist-util-visit/index.js:48:26)
>     at one (/Users/sobolev/Documents/github/awesome-cryptography/node_modules/unist-util-visit/index.js:76:20)
>     at all (/Users/sobolev/Documents/github/awesome-cryptography/node_modules/unist-util-visit/index.js:48:26)
>     at one (/Users/sobolev/Documents/github/awesome-cryptography/node_modules/unist-util-visit/index.js:76:20)
>     at visit (/Users/sobolev/Documents/github/awesome-cryptography/node_modules/unist-util-visit/index.js:82:5)
>     at checkURL (/Users/sobolev/Documents/github/awesome-cryptography/node_modules/remark-lint-no-url-trailing-slash/dist/resource-url.js:7:3)
> 
> ✖ 2 errors
> npm ERR! Test failed.  See above for more details.

**Comment by vhf** [comment]
Thanks for the bug report. This plugin is compatible with remark 3.x, remark 4.x changed the `href` node property to a `url` property.

I'll publish a new version with the remark 4.x fix asap.

**Comment by sobolevn** [comment]
I could send a PR.

**Comment by vhf** [comment]
I just published the `2.0.0` tag. I tested on your repo, it works properly:

```
/tmp/awesome-cryptography master* ⇣
❯ ./node_modules/remark/bin/remark README.md CONTRIBUTING.md -f
README.md
  7:1-48:22     warning  Alphabetical ordering: line 20 should be somewhere higher in the list
  7:1-48:22     warning  Alphabetical ordering: line 22 should be somewhere higher in the list
  7:1-48:22     warning  Alphabetical ordering: line 46 should be somewhere higher in the list
  11:5-12:40    warning  Alphabetical ordering: line 12 should be somewhere higher in the list
  73:3-73:41    warning  Remove trailing slash (https://www.crypto101.io)                       trailing-slash
  90:3-90:32    warning  Remove trailing slash (https://www.gnupg.org)                          trailing-slash
  96:3-96:39    warning  Remove trailing slash (http://www.cryptlib.com)                        trailing-slash
  99:3-99:33    warning  Remove trailing slash (https://nacl.cr.yp.to)                          trailing-slash
  107:3-107:43  warning  Remove trailing slash (http://bcrypt.sourceforge.net)                  trailing-slash
  108:3-108:40  warning  Remove trailing slash (https://botan.randombit.net)                    trailing-slash
  109:3-109:40  warning  Remove trailing slash (https://www.cryptopp.com)                       trailing-slash
  177:3-177:43  warning  Remove trailing slash (http://shiro.apache.org)                        trailing-slash
  210:3-210:39  warning  Remove trailing slash (http://www.paramiko.org)                        trailing-slash
```

**Comment by sobolevn** [comment]
Thanks!

**Comment by vhf** [comment]
I updated the README with remark version info, just in case: https://github.com/vhf/remark-lint-no-url-trailing-slash#check-which-remark-version-youre-using

Thanks for the bug report. :)
